#!/bin/bash
#
#SBATCH --job-name=G_22
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=500:00
#SBATCH --mem=10GB

module purge
module load gaussian/intel/g09e01

srun run-gaussian ../test/confs_smiles/ginput/241.opt.com > ../test/confs_smiles/ginput/241.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/242.opt.com > ../test/confs_smiles/ginput/242.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/243.opt.com > ../test/confs_smiles/ginput/243.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/244.opt.com > ../test/confs_smiles/ginput/244.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/245.opt.com > ../test/confs_smiles/ginput/245.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/246.opt.com > ../test/confs_smiles/ginput/246.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/247.opt.com > ../test/confs_smiles/ginput/247.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/248.opt.com > ../test/confs_smiles/ginput/248.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/249.opt.com > ../test/confs_smiles/ginput/249.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/250.opt.com > ../test/confs_smiles/ginput/250.opt.log 2>&1
