#!/bin/bash
#
#SBATCH --job-name=G_23
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=5:00:00
#SBATCH --mem=10GB

module purge
module load gaussian/intel/g09e01

srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/251.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/251.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/252.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/252.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/253.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/253.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/254.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/254.opt.log 2>&1
