#!/bin/bash
#
#SBATCH --job-name=G_11
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=500:00
#SBATCH --mem=10GB

module purge
module load gaussian/intel/g09e01

srun run-gaussian ../test/confs_smiles/ginput/131.opt.com > ../test/confs_smiles/ginput/131.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/132.opt.com > ../test/confs_smiles/ginput/132.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/133.opt.com > ../test/confs_smiles/ginput/133.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/134.opt.com > ../test/confs_smiles/ginput/134.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/135.opt.com > ../test/confs_smiles/ginput/135.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/136.opt.com > ../test/confs_smiles/ginput/136.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/137.opt.com > ../test/confs_smiles/ginput/137.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/138.opt.com > ../test/confs_smiles/ginput/138.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/139.opt.com > ../test/confs_smiles/ginput/139.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/140.opt.com > ../test/confs_smiles/ginput/140.opt.log 2>&1
