#!/bin/bash
#
#SBATCH --job-name=G_12
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=5:00:00
#SBATCH --mem=10GB

module purge
module load gaussian/intel/g09e01

srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/141.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/141.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/142.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/142.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/143.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/143.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/144.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/144.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/145.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/145.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/146.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/146.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/147.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/147.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/148.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/148.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/149.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/149.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/150.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/150.opt.log 2>&1
