#!/bin/bash
#
#SBATCH --job-name=G_15
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=5:00:00
#SBATCH --mem=10GB

module purge
module load gaussian/intel/g09e01

srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/171.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/171.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/172.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/172.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/173.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/173.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/174.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/174.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/175.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/175.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/176.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/176.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/177.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/177.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/178.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/178.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/179.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/179.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/180.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/180.opt.log 2>&1
