#!/bin/bash
#
#SBATCH --job-name=G_8
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=5:00:00
#SBATCH --mem=10GB

module purge
module load gaussian/intel/g09e01

srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/101.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/101.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/102.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/102.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/103.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/103.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/104.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/104.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/105.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/105.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/106.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/106.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/107.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/107.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/108.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/108.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/109.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/109.opt.log 2>&1
srun run-gaussian /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/110.opt.com > /beegfs/jl7003/1Dto3D_DataGen/test/confs_smiles/ginput/110.opt.log 2>&1
