#!/bin/bash
#
#SBATCH --job-name=G_10
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=500:00
#SBATCH --mem=10GB

module purge
module load gaussian/intel/g09e01

srun run-gaussian ../test/confs_smiles/ginput/121.opt.com > ../test/confs_smiles/ginput/121.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/122.opt.com > ../test/confs_smiles/ginput/122.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/123.opt.com > ../test/confs_smiles/ginput/123.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/124.opt.com > ../test/confs_smiles/ginput/124.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/125.opt.com > ../test/confs_smiles/ginput/125.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/126.opt.com > ../test/confs_smiles/ginput/126.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/127.opt.com > ../test/confs_smiles/ginput/127.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/128.opt.com > ../test/confs_smiles/ginput/128.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/129.opt.com > ../test/confs_smiles/ginput/129.opt.log 2>&1
srun run-gaussian ../test/confs_smiles/ginput/130.opt.com > ../test/confs_smiles/ginput/130.opt.log 2>&1
